### ISSUE TITLE
Vulnerabilities identified in code scan

### ISSUE THREAD

**Issue by JCPriyanka123** [sambetts/SPOColdStorage#4]
Need to know how to fix the High and Medium priority issues raised Snyk. Connected to Project directly from Git and gives below result when scanned.
![SnykVulnerabilities](https://github.com/sambetts/SPOColdStorage/assets/133353585/bb0c2389-918e-477c-b6f8-aa6365835b73)

**Comment by JCPriyanka123** [comment]
Can you please provide an update on the above issue

**Comment by sambetts** [comment]
Feel free to create a PR.
